### ISSUE TITLE
Content type selection while searching always returns all types of content.

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#67] opened 2021-01-08 22:31 UTC
Selecting different types of content to search for has no effect on the results. Here I compare search for 'country music' playlists in the application and directly on YouTube.
![playlistsearchapp](https://user-images.githubusercontent.com/36137483/104071159-6af45b80-51bd-11eb-9119-640102605abd.PNG)
_Note the **videos** in results_
![playlistsearchweb](https://user-images.githubusercontent.com/36137483/104071163-6d56b580-51bd-11eb-89ea-b983341ba35b.PNG)
The application results match the general search on YouTube:
![generalsearchweb](https://user-images.githubusercontent.com/36137483/104071343-d76f5a80-51bd-11eb-9369-d050bcc3b678.PNG)

This applies for all types of content, not only playlists. Searching for channels will still return general search results.

Platform: Windows 10
Java: 1.8.0_271 (Oracle)

Ran both using the release 1.4.3 jar file and compiled from source myself.

**Comment by mattwright324** [comment] 2021-01-08 22:42
I am able to reproduce, thanks @kacper1112 

https://github.com/mattwright324/youtube-comment-suite/blob/aeabc826d72c833a279c8cf16ec63037e9422b5c/src/main/java/io/mattw/youtube/commentsuite/fxml/SearchYouTube.java#L198-L204

The issue appears to be because I accidentally was sending the `type` Normal/Location instead of the `searchType` video/playlist/channel. 

I have this fixed in a commit to the develop branch c29b6c3d5962f245ecf6acb8be9a69de0ecabe64 and will be in the next release.

**Closed** 2021-01-24 02:52 UTC
Labels: bug, resolved
