### ISSUE TITLE
Trying to create a new group with an empty name creates unclosable pop up.

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#64] opened 2021-01-08 21:44 UTC
After trying to create a new group with an empty name, the application goes into state below:
![empty_groupname](https://user-images.githubusercontent.com/36137483/104066282-01248380-51b6-11eb-8bb2-48aae6c0c99c.PNG)
It is impossible to interact in any way with the group creation pop up, it becomes 'transparent' - the background buttons and text fields can be used. The pop window is only visible in the Group Management tab.

Clicking the plus icon again only changes the pop up to look like this. It is still impossible to interact with  it.
![empty_groupname_plus](https://user-images.githubusercontent.com/36137483/104067116-6e84e400-51b7-11eb-8e07-e516ebfff532.PNG)

Platform: Windows 10
Java: 1.8.0_271 (Oracle)

Ran both using the release 1.4.3 jar file and compiled from source myself.

**Comment by mattwright324** [comment] 2021-01-08 21:55
Thanks @kacper1112 

This seems to have been caused by a copy-paste and not updating a value. Should be `false` here and not `true`.

https://github.com/mattwright324/youtube-comment-suite/blob/aeabc826d72c833a279c8cf16ec63037e9422b5c/src/main/java/io/mattw/youtube/commentsuite/fxml/ManageGroups.java#L143

I have this fixed in a commit to the `develop` branch 9f9e4423ae3568042959c3bbf1b7a0c431171c3b and will be in the next release.

**Closed** 2021-01-24 02:52 UTC
Labels: bug, resolved
