### ISSUE TITLE
Messages missing from export

### ISSUE THREAD

**Issue by bernard01** [mattwright324/youtube-comment-suite#84] opened 2021-07-21 23:28 UTC
My apologies for incomplete information at this stage.
In 1.4.6, I am exporting to CSV. It appears that this has been working very well in older versions.
Also I find that message search results work very well. I need the searches to test the export results. My database contains older messages from videos that are deleted from YouTube. These videos generate error messages on the Refresh action as expected. These older messages are important to me. I can find them with message searches so I know they are still in the database.
When I run the export, then it appears that a limiting search does not limit the number of messages exported. Therefore it is difficult to verify / test my scenario.
So when I export, I get a large number of files. When I process these json files, then I find that the number of messages in them is roughly the number of messages that I would expect. But there are many duplicate messages. When I eliminate the duplicate messages, then I find that only half the number of messages I expect is exported, and especially the latest messages are missing. The oldest messages are still there. So I run a text search over the export directory searching for the newer missing message IDs. Not found.
I have not debugged or analyzed the source code. I thought it might be appropriate to first describe the problem to discuss it.

**Comment by mattwright324** [comment] 2021-07-22 13:32
Hey @bernard01

Redesigning and updating the export functionality is certainly on my list to do next.

As for what is happening in the latest version, I am not expecting it to export comments in duplicate. Could you give an example of what this looks like? A limiting search should limit the number of results in the export though you'd need to hit search with those options before the export for that to happen. This might not be obvious, did you click search with your limiting options before exporting?

**Comment by bernard01** [comment] 2021-07-25 09:13
Sorry for the delay. I cannot see anything wrong with the database. So I uploaded it. Perhaps you can use it. 
https://mega.nz/folder/PARyAB5a#De7Z4ElR4iM5Mrd1NW7LUQ
For the full export, I export after a search with defaults set, meaning everything.
I search in the default group, using all default settings.
Then I click The Export Results button.
Again, default Flattened then Export to JSON
Opens the folder in Explorer which is good.

Now I copy the latest comment ID in the search:
UgwlCcYTMQ2LwYfac9x4AaABAg.8y_vwNkHcTf9QD4G82a1K4

Then in that export directory, I do a simple text search for that ID.

It is found in 6 files:

86ftQ0CmvE8-comments.json
M742Um1Poh4-comments.json
VgnySF63FDs-comments.json
h-iUT9cih-w-comments.json
huTz7b2wmRI-comments.json
jwg4czkDH-o-comments.json

There is more going on as I wrote and I am confused, but I thought I better keep it simple.
Thanks a lot.

**Comment by mattwright324** [comment] 2021-07-25 15:12
There definitely seems to be something weird going on. When I try a completely default search and export like you described, I am not seeing an issue. However, when I try exports with limiting criteria and try to find comment ids from the in-app search I do not see them in the exported files and the ones that are in the export seem to be in duplicate. Looking into the cause now, thanks!

**Comment by mattwright324** [comment] 2021-07-31 15:20
The issue seems to have been caused by using my thread-unsafe comment query in the multi-threaded export in the wrong way. Each thread is given its own video to export but the query was being reused across all threads so it would put comments from one video into multiple files (duplicate comments in wrong video files) and not finish or even start on some videos because the video it was supposed to export changed (comments missing). 

I have this fixed in commit 2dcae8c13b633d436e091a1962697e5e83a954ca and will be out in the next release.

**Comment by bernard01** [comment] 2021-08-02 00:30
Thanks. I guess I could write an export from a query myself, but I could not find an easy way to get the date out in a readable format. So I use the JSON and parse that.
Really great software. Have been using it to hunt a criminal, a scammer. This is the only way to see their HUNDREDS of fake sock puppet shill accounts. With the support of your  database. I wonder how they can handle so many accounts. With my awareness campaign, I am running into YouTube spam rule limitations with only a handful of accounts. The scammer has an advantage because he never runs against these limits.

**Comment by mattwright324** [comment] 2021-08-02 01:15
I did happen to notice all of the spam comments with multiple accounts while I was fixing the issue using the archive you provided to test with. It's cool to see the tool allows you to research that kind of thing!

I agree that the stored date format in the database is not ideal and the more readable ISO 8601 format it is converted to (and exported as) is much better. This is due to using the older "Date" class and its milliseconds timestamp originally before I knew about the better Java 8 Date and Time API.

**Closed** 2021-08-03 01:09 UTC
Labels: bug, resolved
