### ISSUE TITLE
Export Comments to Excel

### ISSUE THREAD

**Issue by kostasall12** [mattwright324/youtube-comment-suite#75] opened 2021-03-03 18:52 UTC
Hello .

 Is there a way to export all youtube comments to word or excel file?

**Comment by mattwright324** [comment] 2021-03-03 19:57
Duplicate of #35 

This is on my list of things to do, currently the only export method is JSON. It definitely would be useful to have an export to CSV format and possibly other options for the export.

**Closed by mattwright324** 2021-03-03 19:57 UTC
Labels: enhancement

**Comment by mattwright324** [comment] 2021-08-02 17:36
I have a working version of CSV export and it will be out in the next release.
