### ISSUE TITLE
Export to Spreadsheet

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [mattwright324/youtube-comment-suite#83] opened 2021-05-03 21:06 UTC
Please consider adding an option to export all comments from a YouTube video/YouTube channel to a spreadsheet document.

**Comment by Himusaki** [comment] 2021-05-10 05:47
I want the same feature 
Tired of JSON.

@mattwright324 Plz help us again.

Thanks alot for your hard work

**Comment by Himusaki** [comment] 2021-05-16 03:54
@mattwright324 please at least reply.

**Comment by mattwright324** [comment] 2021-08-01 18:56
Duplicate of #35

Closing this and will update progress on the other issue. I will note that I am working on this right now, there will be an option to export as JSON or CSV soon.

**Closed by mattwright324** 2021-08-01 18:56 UTC
Labels: enhancement

**Comment by mattwright324** [comment] 2021-08-02 17:35
I have a working version of CSV export and it will be out in the next release.
